// <auto-generated />
using System;
using CJTasksHelperBot.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CJTasksHelperBot.Persistence.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteApplicationDbContext))]
    [Migration("20240308154051_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2");

            modelBuilder.Entity("CJTasksHelperBot.Domain.Entities.Chat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("CJTasksHelperBot.Domain.Entities.Homework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Task")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserChatChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserChatUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserChatUserId", "UserChatChatId");

                    b.ToTable("Homework");
                });

            modelBuilder.Entity("CJTasksHelperBot.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserChatChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserChatUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserChatUserId", "UserChatChatId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CJTasksHelperBot.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CJTasksHelperBot.Domain.Entities.UserChat", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "ChatId");

                    b.HasIndex("ChatId");

                    b.ToTable("UserChats");
                });

            modelBuilder.Entity("CJTasksHelperBot.Domain.Entities.Homework", b =>
                {
                    b.HasOne("CJTasksHelperBot.Domain.Entities.User", null)
                        .WithMany("Homeworks")
                        .HasForeignKey("UserId");

                    b.HasOne("CJTasksHelperBot.Domain.Entities.UserChat", "UserChat")
                        .WithMany()
                        .HasForeignKey("UserChatUserId", "UserChatChatId");

                    b.Navigation("UserChat");
                });

            modelBuilder.Entity("CJTasksHelperBot.Domain.Entities.Task", b =>
                {
                    b.HasOne("CJTasksHelperBot.Domain.Entities.User", null)
                        .WithMany("Tasks")
                        .HasForeignKey("UserId");

                    b.HasOne("CJTasksHelperBot.Domain.Entities.UserChat", "UserChat")
                        .WithMany()
                        .HasForeignKey("UserChatUserId", "UserChatChatId");

                    b.Navigation("UserChat");
                });

            modelBuilder.Entity("CJTasksHelperBot.Domain.Entities.UserChat", b =>
                {
                    b.HasOne("CJTasksHelperBot.Domain.Entities.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CJTasksHelperBot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CJTasksHelperBot.Domain.Entities.User", b =>
                {
                    b.Navigation("Homeworks");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
