//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJTasksHelperBot.Infrastructure.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_uk {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_uk() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CJTasksHelperBot.Infrastructure.Resources.Messages_uk", typeof(Messages_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string help_message {
            get {
                return ResourceManager.GetString("help_message", resourceCulture);
            }
        }
        
        internal static string table_cell_name {
            get {
                return ResourceManager.GetString("table_cell_name", resourceCulture);
            }
        }
        
        internal static string table_cell_deadline {
            get {
                return ResourceManager.GetString("table_cell_deadline", resourceCulture);
            }
        }
        
        internal static string table_cell_description {
            get {
                return ResourceManager.GetString("table_cell_description", resourceCulture);
            }
        }
        
        internal static string table_cell_status {
            get {
                return ResourceManager.GetString("table_cell_status", resourceCulture);
            }
        }
        
        internal static string in_table_view {
            get {
                return ResourceManager.GetString("in_table_view", resourceCulture);
            }
        }
        
        internal static string wrng_val_enter_again {
            get {
                return ResourceManager.GetString("wrng_val_enter_again", resourceCulture);
            }
        }
        
        internal static string comm_succ_int {
            get {
                return ResourceManager.GetString("comm_succ_int", resourceCulture);
            }
        }
        
        internal static string enter_task_desc {
            get {
                return ResourceManager.GetString("enter_task_desc", resourceCulture);
            }
        }
        
        internal static string enter_task_deadline {
            get {
                return ResourceManager.GetString("enter_task_deadline", resourceCulture);
            }
        }
        
        internal static string word_example {
            get {
                return ResourceManager.GetString("word_example", resourceCulture);
            }
        }
        
        internal static string wrong_datetime_try_again {
            get {
                return ResourceManager.GetString("wrong_datetime_try_again", resourceCulture);
            }
        }
        
        internal static string err_creat_task_try_again {
            get {
                return ResourceManager.GetString("err_creat_task_try_again", resourceCulture);
            }
        }
        
        internal static string task_created {
            get {
                return ResourceManager.GetString("task_created", resourceCulture);
            }
        }
        
        internal static string usage {
            get {
                return ResourceManager.GetString("usage", resourceCulture);
            }
        }
        
        internal static string no_tasks {
            get {
                return ResourceManager.GetString("no_tasks", resourceCulture);
            }
        }
        
        internal static string word_by {
            get {
                return ResourceManager.GetString("word_by", resourceCulture);
            }
        }
        
        internal static string word_status {
            get {
                return ResourceManager.GetString("word_status", resourceCulture);
            }
        }
        
        internal static string word_personal {
            get {
                return ResourceManager.GetString("word_personal", resourceCulture);
            }
        }
        
        internal static string to_int_enter {
            get {
                return ResourceManager.GetString("to_int_enter", resourceCulture);
            }
        }
        
        internal static string need_enter_lang_code {
            get {
                return ResourceManager.GetString("need_enter_lang_code", resourceCulture);
            }
        }
        
        internal static string enter_lang_code {
            get {
                return ResourceManager.GetString("enter_lang_code", resourceCulture);
            }
        }
        
        internal static string choose_lang {
            get {
                return ResourceManager.GetString("choose_lang", resourceCulture);
            }
        }
        
        internal static string enter_task_name {
            get {
                return ResourceManager.GetString("enter_task_name", resourceCulture);
            }
        }
        
        internal static string need_enter_task_name {
            get {
                return ResourceManager.GetString("need_enter_task_name", resourceCulture);
            }
        }
        
        internal static string only_for_admins {
            get {
                return ResourceManager.GetString("only_for_admins", resourceCulture);
            }
        }
        
        internal static string NotLevelWeek {
            get {
                return ResourceManager.GetString("NotLevelWeek", resourceCulture);
            }
        }
        
        internal static string NotLevelTwoDays {
            get {
                return ResourceManager.GetString("NotLevelTwoDays", resourceCulture);
            }
        }
        
        internal static string NotLevelDay {
            get {
                return ResourceManager.GetString("NotLevelDay", resourceCulture);
            }
        }
        
        internal static string deadline_notification_reminder {
            get {
                return ResourceManager.GetString("deadline_notification_reminder", resourceCulture);
            }
        }
        
        internal static string word_group {
            get {
                return ResourceManager.GetString("word_group", resourceCulture);
            }
        }
        
        internal static string TaskNotStarted {
            get {
                return ResourceManager.GetString("TaskNotStarted", resourceCulture);
            }
        }
        
        internal static string TaskInProgress {
            get {
                return ResourceManager.GetString("TaskInProgress", resourceCulture);
            }
        }
        
        internal static string TaskAlmostDone {
            get {
                return ResourceManager.GetString("TaskAlmostDone", resourceCulture);
            }
        }
        
        internal static string TaskCompleted {
            get {
                return ResourceManager.GetString("TaskCompleted", resourceCulture);
            }
        }
        
        internal static string TaskDeadlineMissed {
            get {
                return ResourceManager.GetString("TaskDeadlineMissed", resourceCulture);
            }
        }
        
        internal static string TaskCompletedWithMissedDeadline {
            get {
                return ResourceManager.GetString("TaskCompletedWithMissedDeadline", resourceCulture);
            }
        }
        
        internal static string word_all {
            get {
                return ResourceManager.GetString("word_all", resourceCulture);
            }
        }
        
        internal static string choose_status {
            get {
                return ResourceManager.GetString("choose_status", resourceCulture);
            }
        }
        
        internal static string choose_chat_or_params {
            get {
                return ResourceManager.GetString("choose_chat_or_params", resourceCulture);
            }
        }
        
        internal static string only_in_private {
            get {
                return ResourceManager.GetString("only_in_private", resourceCulture);
            }
        }
        
        internal static string enter_partial_task_id {
            get {
                return ResourceManager.GetString("enter_partial_task_id", resourceCulture);
            }
        }
        
        internal static string enter_partial_task_title {
            get {
                return ResourceManager.GetString("enter_partial_task_title", resourceCulture);
            }
        }
        
        internal static string enter_new_task_status {
            get {
                return ResourceManager.GetString("enter_new_task_status", resourceCulture);
            }
        }
        
        internal static string err_update_task_status_try_again {
            get {
                return ResourceManager.GetString("err_update_task_status_try_again", resourceCulture);
            }
        }
        
        internal static string incorrect_task_status_try_again {
            get {
                return ResourceManager.GetString("incorrect_task_status_try_again", resourceCulture);
            }
        }
        
        internal static string task_status_updated {
            get {
                return ResourceManager.GetString("task_status_updated", resourceCulture);
            }
        }
        
        internal static string need_enter_partial_task_id {
            get {
                return ResourceManager.GetString("need_enter_partial_task_id", resourceCulture);
            }
        }
        
        internal static string HelpAddTask {
            get {
                return ResourceManager.GetString("HelpAddTask", resourceCulture);
            }
        }
        
        internal static string HelpGetTasks {
            get {
                return ResourceManager.GetString("HelpGetTasks", resourceCulture);
            }
        }
        
        internal static string HelpChangeLanguage {
            get {
                return ResourceManager.GetString("HelpChangeLanguage", resourceCulture);
            }
        }
        
        internal static string HelpUpdateTaskStatus {
            get {
                return ResourceManager.GetString("HelpUpdateTaskStatus", resourceCulture);
            }
        }
    }
}
